### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by ixearth** [baron0668/demoo#1]
Thanks this script is very useful.

Currently the script require python2, and need to install `pycrypt` the package. It does not require any package if the script was written in python3.

I don't know python. I have tried to convert the script by using [2to3](https://docs.python.org/2/library/2to3.html) and edited it to execute without produce any error. but the output epub have some problems.

It shows this error above each title of chapter in Apple Books.
> “This page contains the following errors:
> error on line 29 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.”

Can you fix this script? or rewrite a python3 one?
[test.py.zip](https://github.com/baron0668/demoo/files/3907284/test.py.zip)

btw the database path have been changed on macOS Catalina. should be 
`dbPath = homePath + "/Library/Containers/com.readmoo.readmoodesktop/Data/Library/Application Support/Readmoo/Local Storage/" + "app_readmoo_0.localstorage"`

**Comment by Anonymous-Hentai** [comment]
@ixearth https://github.com/baron0668/demoo/pull/2

Done.

**Comment by baron0668** [comment]
Close issue.
